{{- range .Values.kinesis.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "openshift-logforwarding-kinesis.fullname" . }}
  labels:
    app.kubernetes.io/component: fluentd
{{ include "openshift-logforwarding-kinesis.labels" . | indent 4 }}
type: Opaque
data:
  fluentd-ssl-passsphrase: {{ .Values.forwarding.fluentd.passphrase | b64enc | quote }}
  shared_key: {{ .Values.forwarding.fluentd.sharedkey | b64enc | quote }}

{{- if .Values.forwarding.fluentd.ssl }}
{{- $fluentdCaFile := .Files.Get .Values.forwarding.fluentd.caFile }}
{{- $fluentdKeyFile := .Files.Get .Values.forwarding.fluentd.keyFile }}
{{- if or (not $fluentdCaFile) (not $fluentdKeyFile) -}}
{{- fail "Could not locate Fluentd Certificate or Private key" }}
{{ end }}
  tls.crt: {{ $fluentdCaFile | b64enc }}
  tls.key: {{ $fluentdKeyFile | b64enc }}
  ca-bundle.crt: {{ $fluentdCaFile | b64enc }}
{{ end }}
{{ end -}}