{{ $params:= . }}
{{ range $index, $kinesis := .Values.kinesis }}
{{- if $kinesis.isenabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: logforwarding-kinesis-{{ $kinesis.name }}
  labels:
    app.kubernetes.io/component: fluentd
type: Opaque
data:
  fluentd_ssl_passsphrase: {{ $kinesis.tlspassphrase | b64enc | quote }}
  shared_key: {{ $kinesis.fluentd_sharedkey | b64enc | quote }}
{{- if $kinesis.ssl }}
{{- $fluentdCaFile := .Files.Get $kinesis.caFile }}
{{- $fluentdKeyFile := .Files.Get $kinesis.keyFile }}
{{- if or (not $fluentdCaFile) (not $fluentdKeyFile) -}}
{{- fail "Could not locate Fluentd Certificate or Private key" }}
{{ end }}
  tls.crt: {{ $fluentdCaFile | b64enc }}
  tls.key: {{ $fluentdKeyFile | b64enc }}
  ca-bundle.crt: {{ $fluentdCaFile | b64enc }}
{{ end }}
{{ end }}
{{ end }}
