apiVersion: v2
name: openshift-logforwarding-kinesis
description: Log Forwarding from OpenShift to AWS Kinesis
type: application
version: 0.0.1
appVersion: 0.0.1
maintainers:
- email: scott.c.worthington@gmail.com
  name: Scott Worthington