kind: Deployment
apiVersion: apps/v1
metadata:
  name: log-forwarding-kinesis
  namespace: openshift-logging
  labels:
    app: log-forwarding-kinesis
    app.kubernetes.io/component: log-forwarding-kinesis
    app.kubernetes.io/instance: log-forwarding-kinesis
    app.kubernetes.io/part-of: log-forwarding-kinesis
spec:
  replicas: 2
  selector:
    matchLabels:
      app: log-forwarding-kinesis
  template:
    metadata:
      labels:
        app: log-forwarding-kinesis
    spec:
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      containers:
        - resources:
            requests:
              cpu: 100m
              memory: 200Mi
          terminationMessagePath: /dev/termination-log
          name: log-forwarding-kinesis
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
          imagePullPolicy: Always
          volumeMounts:
            - name: log-forwarding-kinesis-config
              readOnly: true
              mountPath: /etc/fluent/
          terminationMessagePolicy: File
          image: >-
            quay.io/worsco/ocp4-fluentd-kinesis-forwarder:latest
          args:
            - scl
            - enable
            - rh-ruby25
            - "--"
            - fluentd
      volumes:
        - name: log-forwarding-kinesis-config
          configMap:
            name: log-forwarding-kinesis-config
            items:
              - key: td-agent.conf
                path: fluent.conf
            defaultMode: 420
            optional: true
      dnsPolicy: ClusterFirst
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
