kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: ose-logging-fluentd
  namespace: openshift
spec:
  lookupPolicy:
    local: false
  tags:
    - name: 'v4.3.22-202005201238'
      annotations: null
      from:
        kind: DockerImage
        name: 'registry.redhat.io/openshift4/ose-logging-fluentd:v4.3.22-202005201238'
      importPolicy:
        scheduled: true
      referencePolicy:
        type: Local
