apiVersion: logging.openshift.io/v1alpha1
kind: LogForwarding
metadata:
  name: instance
  namespace: openshift-logging
spec:
  disableDefaultForwarding: true
  outputs:
    - name: elasticsearch
      endpoint: "elasticsearch.openshift-logging.svc.cluster.local:9200"
      secret:
        name: fluentd
      type: elasticsearch
    - name: log-forwarding-kinesis-projects
      endpoint: "log-forwarding-kinesis-projects.openshift-logging.svc:24224"
      type: forward
      secret:
        name: log-forwarding-kinesis-secure-projects
    - name: log-forwarding-kinesis-operations
      endpoint: "log-forwarding-kinesis-operations.openshift-logging.svc:24224"
      type: forward
      secret:
        name: log-forwarding-kinesis-secure-operations
    - name: log-forwarding-kinesis-audit
      endpoint: "log-forwarding-kinesis-audit.openshift-logging.svc:24224"
      type: forward
      secret:
        name: log-forwarding-kinesis-secure-audit
  pipelines:
    - name: container-logs
      inputSource: logs.app
      outputRefs:
        - elasticsearch
        - log-forwarding-kinesis-projects
    - name: infra-logs
      inputSource: logs.infra
      outputRefs:
        - elasticsearch
        - log-forwarding-kinesis-operations
    - name: audit-logs
      inputSource: logs.audit
      outputRefs:
        - log-forwarding-kinesis-audit
