apiVersion: v1
kind: Service
metadata:
  name: log-forwarding-kinesis-SERVICENAME
  namespace: openshift-logging
spec:
  ports:
  - port: 24224
    protocol: TCP
    targetPort: 24224
  selector:
    app: log-forwarding-kinesis-SERVICENAME
